### ISSUE TITLE
Java编译运行样例

### ISSUE THREAD

**Issue by RominYue** [HIT-SCIR/ltp4j#11]
Hello，文档中没有给出具体过程，这一块的知识也不太熟悉。
请问：
       添加完LD_LIBRARY_PATH路径之后，命令行编译运行的流程是什么，可以解答一下么？

**Comment by RominYue** [comment]
update:
Sorry, 是我自己java方面编译的问题没搞清楚。
再次确认一下，LD_LIBRARY_PATH这个环境变量指向的是 \*jni\*.so所在的路径么？
我们只需要ltp4j.jar 以及对应平台的 \*jni\*.so的文件就可以了吧，其他下载下来的文件都可以删掉了吧？

麻烦了。。。

**Comment by Oneplus** [comment]
是的，就像使用其他jar包一样使用ltp4j。
