### ISSUE TITLE
win10 TDM-GCC 编译错误

### ISSUE THREAD

**Issue by skyhiter** [HIT-SCIR/ltp4j#35]
### ## -----编译平台-------
OS： win10 1709 x64
C++：tdm-gcc， gcc 6.4.0（还装有vs2017）已加入path
JDK：1.8.0 144 x64
maven：3.5.2
-----编译步骤------
1、git clone ltp4j
2、git submodule init
3、git submodule update
4、mvn -Dmaven.test.skip=true
--------------------
前三步没问题，第4步报错（win10 的cmd 和 powershell都不行）：
G:\Projects\ltp4j>mvn -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for edu.hit.ir.ltp4j:ltp4j:nar:0.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 54, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hitscir-ltp4j 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- nar-maven-plugin:3.5.0:nar-validate (default-nar-validate) @ ltp4j ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.695 s
[INFO] Finished at: 2018-01-24T01:23:55+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.0:nar-validate (default-nar-validate) on project ltp4j: Could not launch cmd.exe /X /C "link /?": Error while executing process. Cannot run program "link": CreateProcess error=2, 系统找不到指定的文件。 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
-------------------
google得知，此处问题应该提示没有link，在xml表显示加入g++后仍不work。
倘若在Developer command prompt for vs2017运行，会提示：
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.0:nar-validate (default-nar-validate) on project ltp4j: msvc.windowsSdkVersion not specified and versions cannot be found -> [Help 1]

**Comment by skyhiter** [comment]
update：
已解决。
pom.xml中的nar-maven-plugin版本改为最新版，即3.5.2。
然后打开vs2017的“x64 Native Tools Command Prompt for VS 2017”（注：64位jdk需要x64 native）
此时mvn -Dmaven.test.skip=true编译成功。

**Comment by liu946** [comment]
对，现在已经把模型移除出工程了。测试不能正常进行。

**Comment by xueyuan1990** [comment]
我的也报这个错误msvc.windowsSdkVersion not specified and versions cannot be found ，但是按照上面的方面并没有解决

**Comment by fograinmokey** [comment]
大家试一试修改aol.porperties，改成WIN64
amd64.Windows.msvc.cpp.defines=Windows WIN64 _WINDOWS NOMINMAX BOOST_ALL_NO_LIB
amd64.Windows.msvc.c.defines=Windows WIN64 _WINDOWS NOMINMAX BOOST_ALL_NO_LIB
